spring:
  data:
    mongodb:
      uri: mongodb://customer-user:customer-password@localhost:27017/?authSource=customer
      database: customer
logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
elasticsearch:
  rest:
    hostname: localhost
    port: 9200
    scheme: Http