spring:
  data:
    mongodb:
      uri: mongodb://customer-user:customer-password@localhost:27017/?authSource=customer
      database: customer
elasticsearch:
  rest:
    hostname: localhost
    port: 9200
    scheme: Http
local:
  geolocation:
    key: <key>